; Set up package.el to work with MELPA
(require 'package)

(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))

(package-initialize)
;;(package-refresh-contents)

;; Download Evil
(unless (package-installed-p 'evil)
  (package-install 'evil))

;; Enable Evil
(require 'evil)
(evil-mode 1)

;; Visual appearence
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
(blink-cursor-mode -1)

;; Inhibit splash screen
(setq inhibit-splash-screen t)

;; Start in fullscreen
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;; Line wrap
(global-visual-line-mode t)

;; No backup files
(setq make-backup-files nil)

;; Higlight current line
(global-hl-line-mode +1)

;; statusbar info
(column-number-mode t)
(size-indication-mode t)

;; Switching buffers
(global-set-key (kbd "<s-right>") 'next-buffer)
(global-set-key (kbd "<s-left>") 'previous-buffer)
(global-set-key (kbd "<s-down>") 'buffer-menu)

;; Open the shell with super-enter
(global-set-key (kbd "<s-return>") 'shell)

;; Split horizontally by default
(setq split-width-threshold nil)


;; ORG MODE
;; Headlines should be indented
(setq org-startup-indented t)

;; Stars should be hided
(setq org-hide-leading-stars t)

;; EVIL MODE
;; Custom commands
(evil-ex-define-cmd "q" 'kill-this-buffer)
(evil-ex-define-cmd "quit" 'evil-quit)

(defun borneo/save-and-kill-buffer (arg)
  (interactive "p")
  (save-buffer)
  (kill-this-buffer))

(evil-ex-define-cmd "wq" 'borneo/save-and-kill-buffer)

;; Autogenerated custom variables and faces to a separate file
(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
